sonar.projectKey=AfterQuake
sonar.projectName=AfterQuake
sonar.projectVersion=1.0
sonar.sources=src/
sonar.tests=tests/
sonar.language=cs
sonar.sourceEncoding=UTF-8
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.coverage.exclusions=**/Migrations/**/*
sonar.exclusions=**/Migrations/**/*,**/obj/**/*,**/bin/**/*
